#include "instruction_impl/add.c"
#include "instruction_impl/and.c"
#include "instruction_impl/imm_grp_1A.c"
#include "instruction_impl/lea.c"
#include "instruction_impl/mov.c"
#include "instruction_impl/cmp.c"
#include "instruction_impl/inc_dec.c"
#include "instruction_impl/sub.c"